### ISSUE TITLE
Empty result causes deadlock in cytoscape 3.2

### ISSUE THREAD

**Issue by risserlin** [PathwayCommons/CyPath2#4]
If I search CyPath2 for the protein: P61244
No results are returned.
a pop up appears saying "no matches found"
But before you can click ok a cytoscape task monitor appears saying "eecuting search for  P61244" and never finishes.  Cancelling doesn't help. 
![untitled](https://cloud.githubusercontent.com/assets/3842763/5632088/ea6d0ef2-9599-11e4-85f2-9075568367e5.png)

**Comment by IgorRodchenkov** [comment]
Hi Ruth, all,

Thanks for reporting!
I'll look into it.
This also happens with CyPath2 on Cy v3.1.1.

PS:
BTW, we have at least one related to P61244 pathway from Mirtarbase in the
new experimental/test PC2 instance, see:
http://pathwaycommons.baderlab.org/search?q=P61244&type=pathway
And it's not available via CyPath2 yet
(but, just for fun, if you'd start Cytoscape with a JVM option
-DcPath2Url="http://pathwaycommons.baderlab.org/", you'll get it, I hope)

Best,
Igor.

**Comment by IgorRodchenkov** [comment]
Fixed for Cy 3.2.0. This app is now called CyPathwayCommons and requires Java7, like the Cytoscape 3.2 does (won't work with Java 6).

**Comment by IgorRodchenkov** [comment]
Ruth E. emailed: "I keep getting race conditions even with the new version.  In the below screen shot I can't click on the ok button. I am trying to do a bulk search and I click on AdvancedQuery -> Add to list (with the check availability before adding selected)."

What is "bulk search"... We'll find out and, perhaps, will have to implement a new feature...
